language: c

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='Lua 5.3'
  - LUA='LuaJIT 2.0'

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install luasec
  - sudo luarocks install moonscript
  - sudo luarocks make busted-scm-0.rockspec

script: busted

branches:
  except:
    - gh-pages

notifications:
  slack: olivinelabs:ZFLBu3JQfLAlTn7eNeh7rott
